### PR TITLE
Use `github:` shortcut in Berksfile

### PR DESCRIPTION
**Pull request by evverx**
It's shorter :)
Doesn't require Github ssh credentials for `berks install`

### CODE REVIEW

**Comment by skottler** [comment]
Thanks!

**Comment by dwradcliffe** [comment]
I'm going to have to revert this. For some reason berkshelf is crashing and I can't upload any cookbooks with the git sources in this format. :cry:

**Comment by evverx** [comment]
@dwradcliffe , looks like berkshelf bug.
From [documentation](https://github.com/berkshelf/berkshelf/blob/gh-pages/_includes/index.md#github-location):
```
As of version 1.0.0, you may now use GitHub shorthand to specify a location.
```
Can you tell version of berkshelf? Error message?
I'll try to reproduce.

**Comment by dwradcliffe** [comment]
Version 3.2.1. When I try to upload a cookbook I get the error:

> The lockfile is out of sync! Run `berks install` to sync the lockfile.

**Comment by evverx** [comment]
Upload with `--debug` option show me problems with `duo-security` dependency. There is no `.git` suffix [here](https://github.com/rubygems/rubygems-infrastructure/blob/926859b6d30e372f446220207358b7212ce38c73/Berksfile.lock#L23).

**Pull request merged**
