### PR TITLE
Configure logrotate for use on the app servers

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by indirect** [comment]
👍

**Comment by skottler** [comment]
@dwradcliffe I don't have Chef configured on my machine right now, if this looks good can you 🚢?

Also 👋 👋 👋, hope you're doing well.

**Comment by dwradcliffe** [comment]
The nginx logs on the app servers are already being rotated. The real problem is filebeat is holding on to the file handles after rotation. I've tried a few things but it obviously didn't work.

**Comment by skottler** [comment]
There are two issues here. One is that filebeat is holding onto FD's:

```
filebeat   9988             root   10r      REG              202,1 8295836885    2359347 /applications/rubygems/shared/log/production.log-20160824 (deleted)
```

But yesterday when I went to see what was going on, there were also at least 40GB of logs on disk and no file descriptors were being held open after deletion on the relevant files.

> The nginx logs on the app servers are already being rotated.

Where is this configured in Chef? I can't find it.

**Comment by dwradcliffe** [comment]
Ok it looks like the nginx package provides a default logrotate config which is what we are using on the app servers. It works but it would be better to manage this in chef probably so I'm going to use this after all.

**Pull request merged**
