### PR TITLE
Cache rubygems on travis

### PR DESCRIPTION
**Pull request by sonalkr132**
https://docs.travis-ci.com/user/caching/#Enabling-Bundler-caching

### CODE REVIEW

**Comment by dwradcliffe** [comment]
We have all the gems vendored so we should just install from those instead.

**Comment by sonalkr132** [comment]
I am sorry but I don't know how will it be done. Are you suggesting:
```
bundle install --path vender/cache --local
```

Adding `path` creates a very different directory structure very different than what exists:
```
ruby
    └── 2.3.0
        ├── bin
        ├── build_info
        ├── cache
        ├── doc
        ├── extensions
        │   └── x86_64-linux
        │       └── 2.3.0
        │           └── hitimes-1.2.3
        ├── gems
        │   ├── addressable-2.3.8
        ...
```

**Comment by dwradcliffe** [comment]
I think `bundle install --local` will work

**Comment by sonalkr132** [comment]
> I think bundle install --local will work

Sorry but it doesn't. I added following to travis.yml ([commit](https://github.com/sonalkr132/rubygems-infrastructure/commit/ccb149ac08d8e22694993a604c2f438013e0d6fe) and [build](https://travis-ci.org/sonalkr132/rubygems-infrastructure/builds/139521263#L158))
```
language: ruby
bundler_args: --local
```

[Build following this commit](https://travis-ci.org/sonalkr132/rubygems-infrastructure/builds/139522299#L158) still installed every gem.

**Comment by dwradcliffe** [comment]
This repo is nearly obsolete so I'm closing this.

**Pull request closed without merging**
